package com.lch.general.enums;

public enum AdminSearchFunction {
	featureRequest, EMP_UPDATE, ACTIVATE_DEACTIVATE, EMP_HISTORY, EMP_PASSWORD_RESET, LIST_TIMESHEETS_FOR_ADMIN, EMP_TIMESHEET, 
	SET_EMPLOYEE_RATE, IMMIGRATION_DETAILS, REGENERATE_VALIDATION_EMAIL, SEND_EMAIL_TO_EMPLOYEE, EMPLOYEE_SKILLS, SKILL_SEARCHED_FOR
}
